# Generated by Django 2.0.7 on 2018-07-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=400)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
