# Generated by Django 2.0.7 on 2018-07-16 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='expenses.Expense'),
        ),
    ]
